In [179]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
from IPython.display import Image

In [162]:
#Judul Project dan Identitas Lengkap
print("Judul    : Prediksi Level Obesitas Mengunakan KNN")
print("Nama     : Laurentius Joandanu")
print("NIM      : A11.2022.14179")
print("Kelompok : A11.4419")

Judul    : Prediksi Level Obesitas Mengunakan KNN
Nama     : Laurentius Joandanu
NIM      : A11.2022.14179
Kelompok : A11.4419

In [163]:
# Ringkasan dan Permasalahan
print("Ringkasan dan Permasalahan")
print("Project ini bertujuan untuk memprediksi level obseitas seseorang")
print("Masalah yang ingin diselesaikan adalah untuk mengklasifikan level obesitas seseorang dengan metode KNN")

Ringkasan dan Permasalahan
Project ini bertujuan untuk memprediksi level obseitas seseorang
Masalah yang ingin diselesaikan adalah untuk mengklasifikan level obesitas seseorang dengan metode KNN

In [164]:
# Tujuan
print("Tujuan")
print("Tujuan dari project ini adalah mengembangkan model KNN yang dapat untuk memprediksi level obesitas seseorang")

Tujuan
Tujuan dari project ini adalah mengembangkan model KNN yang dapat untuk memprediksi level obesitas seseorang

In [180]:
# Bagan Alur
url_gambar = 'https://raw.githubusercontent.com/Joandanu/MachineLearning/main/UAS/Bagan.png'
Image(url=url_gambar)

In [183]:
# Dataset
df = pd.read_csv('https://raw.githubusercontent.com/Joandanu/MachineLearning/main/UAS/ObesityDataSet_raw_and_data_sinthetic.csv')
df.head()

,Gender,Age,Height,Weight,family_history_with_overweight,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,NObeyesdad
0,Female,21,1.62,64,yes,no,2,3,Sometimes,no,2,no,0,1,no,Public_Transportation,Normal_Weight
1,Female,21,1.52,56,yes,no,3,3,Sometimes,yes,3,yes,3,0,Sometimes,Public_Transportation,Normal_Weight
2,Male,23,1.8,77,yes,no,2,3,Sometimes,no,2,no,2,1,Frequently,Public_Transportation,Normal_Weight
3,Male,27,1.8,87,no,no,3,3,Sometimes,no,2,no,2,0,Frequently,Walking,Overweight_Level_I
4,Male,22,1.78,89.8,no,no,2,1,Sometimes,no,2,no,0,0,Sometimes,Public_Transportation,Overweight_Level_II

In [184]:
# Penjelasan Dataset
url_gambar = 'https://raw.githubusercontent.com/Joandanu/MachineLearning/main/UAS/Penjelasandataset.png'
Image(url=url_gambar)

In [167]:
# Memuat dan Memproses data
def muat_dan_proses_data(url):
    nama_kolom = ['Gender', 'Age', 'Height', 'Weight', 'family_history_with_overweight', 'FAVC', 'FCVC', 'NCP', 'CAEC', 'SMOKE', 'CH2O', 'SCC', 'FAF', 'TUE', 'CALC', 'MTRANS', 'NObeyesdad']
    df = pd.read_csv(url, header=None, names=nama_kolom)
    X = df.iloc[:, :-1].values
    y = df.iloc[:, -1].values
    return df, X, y

url = "https://raw.githubusercontent.com/Joandanu/MachineLearning/main/UAS/ObesityDataSet_raw_and_data_sinthetic.csv"
df, X, y = muat_dan_proses_data(url)
X_train = pd.DataFrame(df)

In [168]:
# Menghapus data yang sama
df = df.drop_duplicates()
df

,Gender,Age,Height,Weight,family_history_with_overweight,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,NObeyesdad
0,Gender,Age,Height,Weight,family_history_with_overweight,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,NObeyesdad
1,Female,21,1.62,64,yes,no,2,3,Sometimes,no,2,no,0,1,no,Public_Transportation,Normal_Weight
2,Female,21,1.52,56,yes,no,3,3,Sometimes,yes,3,yes,3,0,Sometimes,Public_Transportation,Normal_Weight
3,Male,23,1.8,77,yes,no,2,3,Sometimes,no,2,no,2,1,Frequently,Public_Transportation,Normal_Weight
4,Male,27,1.8,87,no,no,3,3,Sometimes,no,2,no,2,0,Frequently,Walking,Overweight_Level_I
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2107,Female,20.976.842,171.073,131.408.528,yes,yes,3,3,Sometimes,no,1.728.139,no,1.676.269,906.247,Sometimes,Public_Transportation,Obesity_Type_III
2108,Female,21.982.942,1.748.584,133.742.943,yes,yes,3,3,Sometimes,no,200.513,no,134.139,59.927,Sometimes,Public_Transportation,Obesity_Type_III
2109,Female,22.524.036,1.752.206,133.689.352,yes,yes,3,3,Sometimes,no,2.054.193,no,1.414.209,646.288,Sometimes,Public_Transportation,Obesity_Type_III
2110,Female,24.361.936,173.945,133.346.641,yes,yes,3,3,Sometimes,no,2.852.339,no,1.139.107,586.035,Sometimes,Public_Transportation,Obesity_Type_III
2111,Female,23.664.709,1.738.836,133.472.641,yes,yes,3,3,Sometimes,no,2.863.513,no,1.026.452,714.137,Sometimes,Public_Transportation,Obesity_Type_III

In [169]:
# Memisah X_train dan y_train
X_train = df.drop(['NObeyesdad'], axis=1)
y_train = df['NObeyesdad']

In [170]:
# Inisialisasi LabelEncoder untuk setiap kolom
label_encoders = {
    'Gender': LabelEncoder(),
    'family_history_with_overweight': LabelEncoder(),
    'FAVC': LabelEncoder(),
    'CAEC': LabelEncoder(),
    'SMOKE': LabelEncoder(),
    'SCC': LabelEncoder(),
    'CALC': LabelEncoder(),
    'MTRANS': LabelEncoder()
}

# Pisahkan data menjadi fitur dan target
X = df.iloc[:, :-1].copy()
y = df.iloc[:, -1].copy()

# Split data ke training dan testing
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Mengatasi nilai yang hilang dengan mengisi dengan string kosong (atau bisa dengan metode lain)
X_train.fillna('missing', inplace=True)
X_test.fillna('missing', inplace=True)

# Mengubah kolom yang sesuai ke format numerik
for column, le in label_encoders.items():
    if column in X_train.columns:
        X_train[column] = le.fit_transform(X_train[column].astype(str))
        X_test[column] = le.transform(X_test[column].astype(str))

print(X_train.head())
print(X_test.head())

      Gender         Age     Height      Weight  \
44         2          21       1.66          62
693        2          18  1.767.058  51.132.809
1429       2  21.679.158  1.741.393  98.182.498
170        0          45       1.63          77
309        2          20        1.8          75

      family_history_with_overweight  FAVC       FCVC        NCP  CAEC  SMOKE  \
44                                 2     2          2          3     3      2
693                                2     2  2.708.965          3     3      1
1429                               2     2          2  2.978.103     3      1
170                                2     2          2          3     2      1
309                                1     2          3          4     0      1

           CH2O  SCC        FAF        TUE  CALC  MTRANS
44            2    1          1          1     2       4
693   1.873.004    1    121.718          1     3       4
1429  2.668.261    1  2.462.269  1.402.414     4       4
170           1    1          0          0     4       0
309           3    1          2          0     3       4
      Gender         Age     Height       Weight  \
540        0  18.540.535  1.564.568   41.397.378
1479       2  19.515.324  1.879.144  112.932.984
389        2          18       1.78          108
596        2  17.210.933  1.819.557   58.325.122
1888       0   2.596.773  1.603.404  105.031.908

      family_history_with_overweight  FAVC       FCVC        NCP  CAEC  SMOKE  \
540                                1     2  2.658.112          1     3      1
1479                               2     2          2  2.152.733     3      1
389                                2     1          2          3     3      1
596                                2     2     2.5596          4     3      1
1888                               2     2          3          3     3      1

           CH2O  SCC      FAF        TUE  CALC  MTRANS
540   1.298.165    1        0  1.639.326     3       4
1479    253.369    1  917.563  1.285.838     3       4
389           3    1        1          0     4       4
596           2    1        2    331.483     4       0
1888  1.919.473    1   27.101    546.137     3       4

In [171]:
# Fungsi untuk menghapus pemisah ribuan dan mengonversi ke float
def clean_numeric_column(df, column):
    df[column] = df[column].astype(str)
    df[column] = df[column].str.replace('.', '', regex=False)  # Menghapus titik pemisah ribuan
    df[column] = pd.to_numeric(df[column], errors='coerce')   # Mengonversi ke float

# Terapkan fungsi ini pada kolom yang sesuai
columns_to_clean = ['Age', 'Height', 'Weight', 'FCVC', 'NCP', 'CH2O', 'FAF', 'TUE']
for column in columns_to_clean:
    clean_numeric_column(X_train, column)
    clean_numeric_column(X_test, column)

In [172]:
# Memeriksa nilai yang hilang
print(X_train.isnull().sum())
print(X_test.isnull().sum())

Gender                            0
Age                               1
Height                            1
Weight                            1
family_history_with_overweight    0
FAVC                              0
FCVC                              1
NCP                               1
CAEC                              0
SMOKE                             0
CH2O                              1
SCC                               0
FAF                               1
TUE                               1
CALC                              0
MTRANS                            0
dtype: int64
Gender                            0
Age                               0
Height                            0
Weight                            0
family_history_with_overweight    0
FAVC                              0
FCVC                              0
NCP                               0
CAEC                              0
SMOKE                             0
CH2O                              0
SCC                               0
FAF                               0
TUE                               0
CALC                              0
MTRANS                            0
dtype: int64

In [173]:
# Mengisi atau menghapus nilai yang hilang
X_train = X_train.fillna(X_train.mean())
X_test = X_test.fillna(X_test.mean())

In [174]:
#Mencari nilai k terbaik
metrics = []

for k in range(1, 11):
    knn = KNeighborsClassifier(n_neighbors=k)
    knn.fit(X_train, y_train)
    accuracy = knn.score(X_test, y_test)
    metrics.append(accuracy)

best_k = metrics.index(max(metrics)) + 1
best_k

1

In [186]:
#Menghitung Akurasi unutuk nilai k
k_values = list(range(1, 11))

for k in k_values:
    knn = KNeighborsClassifier(n_neighbors=k)
    knn.fit(X_train, y_train)
    predictions = knn.predict(X_test)
    model = knn.score(X_test, y_test)
    print(f"Accuracy for k={k}: {model}")

Accuracy for k=1: 0.8421052631578947
Accuracy for k=2: 0.8157894736842105
Accuracy for k=3: 0.7990430622009569
Accuracy for k=4: 0.8086124401913876
Accuracy for k=5: 0.7942583732057417
Accuracy for k=6: 0.7942583732057417
Accuracy for k=7: 0.7966507177033493
Accuracy for k=8: 0.7870813397129187
Accuracy for k=9: 0.7894736842105263
Accuracy for k=10: 0.7679425837320574

In [191]:
akurasi = accuracy_score(y_test, y_pred)
print(akurasi)

0.37799043062200954

In [187]:
#Mereport hasil classification
print(classification_report(y_test, knn.predict(X_test), zero_division=0))

                     precision    recall  f1-score   support

Insufficient_Weight       0.79      0.82      0.81        56
      Normal_Weight       0.78      0.97      0.86        65
     Obesity_Type_I       0.64      0.78      0.70        59
    Obesity_Type_II       0.84      0.87      0.86        62
   Obesity_Type_III       0.90      0.92      0.91        71
 Overweight_Level_I       0.61      0.45      0.52        51
Overweight_Level_II       0.73      0.44      0.55        54

           accuracy                           0.77       418
          macro avg       0.76      0.75      0.74       418
       weighted avg       0.76      0.77      0.76       418

In [177]:
#evaluasi
df_pred = pd.DataFrame({'y_true':y_test, 'y_pred':y_pred})
df_pred.head(10)

                   y_true               y_pred
540   Insufficient_Weight  Insufficient_Weight
1479       Obesity_Type_I     Obesity_Type_III
389        Obesity_Type_I  Insufficient_Weight
596   Insufficient_Weight  Overweight_Level_II
1888     Obesity_Type_III     Obesity_Type_III
1928     Obesity_Type_III     Obesity_Type_III
243         Normal_Weight  Insufficient_Weight
1850     Obesity_Type_III     Obesity_Type_III
821    Overweight_Level_I  Overweight_Level_II
51          Normal_Weight        Normal_Weight

In [193]:
print("Kesimpulan:")
print("Model KNN berhasil dilatih dan dievaluasi. Model ini mencapai akurasi", akurasi, "pada data uji.")
print("Model ini dapat digunakan untuk memprediksi level obesitas pada seseorang.")

Kesimpulan:
Model KNN berhasil dilatih dan dievaluasi. Model ini mencapai akurasi 0.37799043062200954 pada data uji.
Model ini dapat digunakan untuk memprediksi level obesitas pada seseorang.